# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "angular" do |c|
        c.vm.box = "bskton/web"
        c.vm.network "private_network", ip: "192.168.36.10"
        c.vm.network "forwarded_port", guest: 3000, host: 3000
        c.vm.network "forwarded_port", guest: 3001, host: 3001
        c.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.name = "angular"
        end
        c.vm.provision :shell, path: "bootstrap.sh"
    end
end